# Generated by Django 2.2.5 on 2019-09-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_text', models.CharField(max_length=40)),
                ('nombre_text', models.CharField(max_length=40)),
                ('dni_text', models.CharField(max_length=11)),
            ],
        ),
    ]
