# Generated by Django 2.2.5 on 2019-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ciudad',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='convenio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dirección',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='provincia',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_movil',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_particular',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
