# Generated by Django 2.2.5 on 2019-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_auto_20191004_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='curso',
            name='derexam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
