# Generated by Django 2.2.5 on 2019-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_auto_20191004_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cuota',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='derexam',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
